require 'dotenv'

Dotenv.load
module Config
  TOKEN_API = ENV['TELEGRAM_BOT_API_TOKEN']
  HIRAK_TRASLATOR_API_KEY = ENV['HIRAK_TRASLATOR_API_KEY']
  HIRAK_TRASLATOR_API_HOST = ENV['HIRAK_TRASLATOR_API_HOST']
end
